### ISSUE TITLE
Oversized LiDAR footprints during extraction with PDAL

### ISSUE THREAD

**Issue by FLeroux23** [ignfab/bat3#1]
Hi,
While processing step 2 of Bat3, i.e. LiDAR extraction using PDAL,  I noticed that the resulting LiDAR footprints were abnormally large, as they extended as far down and to the right as possible. I used the default parameters.

In the following figures, the red objects are the building footprints extracted during Bat3 step 1, the white boundary is the extent of the block specified in step 1, the cyan grid is the actual quadtree structure, the grey grid is the LiDAR HD copc index and the dashed rectangles are the resulting LiDAR footprints extracted in step 2.
![p1](https://github.com/user-attachments/assets/0966fe89-1930-4345-ae8c-43928e619b2c)

**Proposed issue fix**
I took a look at the script: "generate_pdal_pipelines.py" and found an issue with the boundary indices at line 39.

PDAL expects bounds to have the following format: 
[ x_min, x_max ], [ y_min, y_max ]

However, Geopandas returns bounds in the following form: 
[ x_min, y_min ], [ x_max, y_max ]

Geopandas boundaries were mistakenly entered into PDAL as they were, without index adjustment. As a result, the LiDAR tiles are much larger than necessary, which increases calculation time. I applied the following correction in my own fork:

bounds = ([b[0], b[1]], [b[2], b[3]])
to:
bounds = ([b[0], b[2]], [b[1], b[3]])

This speeded up processing time and reduced the size of the extracted tiles by around 2.5 GB (the size of the 4 LiDAR tiles has been reduced from 6.86 GB to 4.38 GB)
![p2](https://github.com/user-attachments/assets/a177f425-3cba-4bd8-a81b-a6e108787671)

Can you confirm this was a simple oversight in the code?
Cheers!

**Comment by esgn** [comment]
Hi,

Many thanks for your review. You're absolutely right. This one got through somehow. I've merged your PR.
I will try and push some other minor fixes soon to deal with changes that appeared on IGNF services.

Thanks again for your review

Cheers
